import dotenv from "dotenv";
dotenv.config();

import {
  PrismaClient,
  Role,
  ActivityCategory,
  ActivityStatus,
  PlaceCategory,
  HousingType,
} from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcrypt";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const hashedPassword = await bcrypt.hash("password123", 12);

// ─── HELPERS ────────────────────────────────────────────────────────────────

function buildActivityEmbeddingText(
  title: string,
  description: string,
  tags: string[],
): string {
  return `${title}. ${description} Tags: ${tags.join(", ")}`;
}

function buildUserEmbeddingText(bio: string, interests: string[]): string {
  return `${bio} Interests: ${interests.join(", ")}`;
}

function buildPlaceEmbeddingText(
  name: string,
  description: string,
  tags: string[],
): string {
  return `${name}. ${description} Tags: ${tags.join(", ")}`;
}

// ─── USERS (20) ──────────────────────────────────────────────────────────────
// 8 CITOYEN (locals who host activities), 12 TOURISTE

const usersData = [
  // ── CITOYENS (locals) ──
  {
    email: "sami.mejri@gmail.com",
    fullName: "Sami Mejri",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Born and raised in the Medina of Tunis. I spend my weekends guiding visitors through souks and sharing my passion for Andalusian music and traditional craftsmanship.",
    interests: [
      "medina tours",
      "traditional crafts",
      "Andalusian music",
      "calligraphy",
      "Arabic coffee rituals",
    ],
  },
  {
    email: "fatma.ben.ali@gmail.com",
    fullName: "Fatma Ben Ali",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Professional pastry chef in Sfax with 12 years of experience in traditional Tunisian sweets. I love sharing recipes passed down from my grandmother and hosting cooking circles.",
    interests: [
      "Tunisian pastry",
      "cooking workshops",
      "spice markets",
      "traditional recipes",
      "food history",
    ],
  },
  {
    email: "youssef.trabelsi@gmail.com",
    fullName: "Youssef Trabelsi",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Desert guide based in Douz with 15 years leading camel treks and overnight camps in the Sahara. I know every dune and star in the Grand Erg Oriental.",
    interests: [
      "desert survival",
      "stargazing",
      "camel trekking",
      "Berber culture",
      "sandboarding",
    ],
  },
  {
    email: "leila.chaabane@gmail.com",
    fullName: "Leila Chaabane",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Marine biologist and freediving instructor in Tabarka. I guide snorkeling tours along coral reefs and lead citizen science sessions to monitor sea life.",
    interests: [
      "freediving",
      "marine biology",
      "coral conservation",
      "underwater photography",
      "coastal ecology",
    ],
  },
  {
    email: "karim.gasmi@gmail.com",
    fullName: "Karim Gasmi",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Contemporary artist and art educator in Sidi Bou Said. I run open studios for ceramics, painting, and mosaic work, mixing traditional zellige techniques with modern art.",
    interests: [
      "zellige mosaic",
      "ceramics",
      "contemporary art",
      "street art",
      "art education",
    ],
  },
  {
    email: "nadia.khelifa@gmail.com",
    fullName: "Nadia Khelifa",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Wellness practitioner and hammam specialist in La Marsa. I offer traditional Tunisian hammam rituals, aromatherapy sessions, and workshops on natural beauty remedies.",
    interests: [
      "hammam",
      "aromatherapy",
      "wellness",
      "traditional medicine",
      "natural beauty",
    ],
  },
  {
    email: "omar.ben.youssef@gmail.com",
    fullName: "Omar Ben Youssef",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Historian and archaeologist specializing in Carthaginian and Roman sites. I lead immersive tours of Carthage, Dougga, and El Jem that go far beyond the guidebooks.",
    interests: [
      "Carthaginian history",
      "Roman archaeology",
      "ancient mosaics",
      "numismatics",
      "historical storytelling",
    ],
  },
  {
    email: "amira.bouzid@gmail.com",
    fullName: "Amira Bouzid",
    password: hashedPassword,
    role: Role.CITOYEN,
    bio: "Textile artist and weaver from Gafsa, trained in traditional Berber carpet weaving. I run hands-on workshops teaching the symbolic language of Tunisian kilim patterns.",
    interests: [
      "Berber weaving",
      "kilim patterns",
      "textile art",
      "natural dye",
      "women's craft cooperatives",
    ],
  },

  // ── TOURISTES ──
  {
    email: "emma.richter@gmail.com",
    fullName: "Emma Richter",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Travel writer from Berlin exploring North Africa for six months. Obsessed with authentic street food, living history, and getting off the tourist trail.",
    interests: [
      "street food",
      "historical sites",
      "travel writing",
      "local markets",
      "photography",
    ],
  },
  {
    email: "james.okonkwo@gmail.com",
    fullName: "James Okonkwo",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Software engineer from Lagos on a sabbatical year. I seek adventure sports, desert landscapes, and conversations with locals about culture and daily life.",
    interests: [
      "adventure sports",
      "desert exploration",
      "cultural exchange",
      "hiking",
      "off-road travel",
    ],
  },
  {
    email: "sophia.laurent@gmail.com",
    fullName: "Sophia Laurent",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Parisian art therapist traveling solo. I gravitate towards artisan workshops, spiritual spaces, and slow immersive experiences that connect me with local communities.",
    interests: [
      "artisan crafts",
      "ceramics",
      "meditation",
      "mosques and riads",
      "slow travel",
    ],
  },
  {
    email: "miguel.fernandez@gmail.com",
    fullName: "Miguel Fernandez",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Marine photographer and diver from Barcelona. Visiting Tunisia for its Mediterranean coastline and underwater caves. Always looking for the next dive site.",
    interests: [
      "scuba diving",
      "underwater photography",
      "marine ecosystems",
      "coastal hikes",
      "sailing",
    ],
  },
  {
    email: "yuki.tanaka@gmail.com",
    fullName: "Yuki Tanaka",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Food anthropologist from Tokyo documenting culinary traditions across the Mediterranean. Particularly interested in the crossroads of Berber, Arab, and Andalusian flavors.",
    interests: [
      "culinary history",
      "spice trade routes",
      "fermented foods",
      "food documentation",
      "market culture",
    ],
  },
  {
    email: "ana.santos@gmail.com",
    fullName: "Ana Santos",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Yoga instructor from Lisbon taking a wellness retreat across North Africa. Interested in traditional healing practices, hammam culture, and herbal medicine.",
    interests: [
      "yoga",
      "hammam wellness",
      "herbal healing",
      "meditation retreats",
      "breathwork",
    ],
  },
  {
    email: "lucas.meyer@gmail.com",
    fullName: "Lucas Meyer",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "History teacher from Zurich spending summer retracing Roman and Carthaginian civilizations. Reads Latin, sketches ruins, and believes every stone tells a story.",
    interests: [
      "Roman history",
      "Carthage",
      "ancient archaeology",
      "ruins",
      "historical maps",
    ],
  },
  {
    email: "priya.sharma@gmail.com",
    fullName: "Priya Sharma",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Fashion designer from Mumbai inspired by textile traditions worldwide. Looking for authentic Tunisian weaving, embroidery, and artisan fabric markets.",
    interests: [
      "textile design",
      "embroidery",
      "fashion history",
      "artisan markets",
      "pattern making",
    ],
  },
  {
    email: "noah.williams@gmail.com",
    fullName: "Noah Williams",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Astrophysicist from Cape Town who chases dark skies. I plan every trip around new moon nights and remote desert locations for stargazing and astrophotography.",
    interests: [
      "stargazing",
      "astrophotography",
      "desert camping",
      "light pollution mapping",
      "telescope travel",
    ],
  },
  {
    email: "clara.dubois@gmail.com",
    fullName: "Clara Dubois",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Sustainability consultant from Lyon focused on ecotourism and regenerative travel. I seek community-led tourism projects, permaculture farms, and conservation initiatives.",
    interests: [
      "ecotourism",
      "permaculture",
      "community tourism",
      "sustainable agriculture",
      "conservation",
    ],
  },
  {
    email: "ali.hassan@gmail.com",
    fullName: "Ali Hassan",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Journalist from Cairo on assignment exploring the cultural revival in Tunisian cities. Interested in street art, music scenes, independent bookshops, and youth culture.",
    interests: [
      "street art",
      "music scenes",
      "independent culture",
      "urban photography",
      "youth movements",
    ],
  },
  {
    email: "isabella.rossi@gmail.com",
    fullName: "Isabella Rossi",
    password: hashedPassword,
    role: Role.TOURISTE,
    bio: "Retired botanist from Florence spending a year studying Mediterranean flora. I collect pressed flowers, sketch plants, and follow old pilgrim routes through countryside and hills.",
    interests: [
      "botany",
      "wildflower identification",
      "nature walks",
      "sketching",
      "pilgrimage routes",
    ],
  },
];

// ─── ACTIVITIES (50) ─────────────────────────────────────────────────────────
// creatorIndex refers to index in usersData (0–7 = CITOYEN)

const activitiesData = [
  // ── Sami Mejri (index 0) ── Medina / Heritage
  {
    creatorId: 7,
    title: "Hidden Souks of the Tunis Medina — Dawn Walk",
    description:
      "Join a pre-sunrise walk through the UNESCO-listed Medina before the crowds arrive. We pass through the Souk des Chéchias, the perfumers' alley, and lesser-known craftsmen courtyards rarely visited by tourists. Sami shares oral histories, architectural details, and insider stories that no guidebook contains. Ends with traditional zlabia and mint tea in a century-old café.",
    price: 35,
    date: new Date("2025-09-10T06:00:00Z"),
    location: "Medina of Tunis",
    latitude: 36.7992,
    longitude: 10.1697,
    capacity: 8,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "medina",
      "UNESCO",
      "dawn walk",
      "souk",
      "traditional crafts",
      "oral history",
      "mint tea",
    ],
  },
  {
    creatorId: 7,
    title: "Calligraphy & Arabic Script Workshop in a Medina Riad",
    description:
      "A 3-hour hands-on workshop in a restored 18th-century riad, learning the basics of Arabic calligraphy using traditional reed pens and natural ink. Sami teaches the Naskh and Thuluth scripts, explaining their role in Islamic architecture and manuscript culture. Participants leave with a framed piece of their own work and a set of calligraphy tools.",
    price: 55,
    date: new Date("2025-09-14T10:00:00Z"),
    location: "Medina of Tunis",
    latitude: 36.7985,
    longitude: 10.17,
    capacity: 6,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "calligraphy",
      "Arabic script",
      "riad",
      "Islamic art",
      "traditional craft",
      "hands-on",
    ],
  },
  {
    creatorId: 7,
    title: "Andalusian Music Evening — Malouf Concert and Storytelling",
    description:
      "An intimate evening in a private Medina courtyard featuring a live performance of Malouf, the Tunisian-Andalusian musical tradition brought by exiles from 15th-century Spain. Sami contextualizes each piece with historical storytelling, tracing melodies from Granada to Tunis. Traditional Tunisian dinner is served during the performance.",
    price: 75,
    date: new Date("2025-09-20T19:00:00Z"),
    location: "Medina of Tunis",
    latitude: 36.799,
    longitude: 10.1695,
    capacity: 15,
    category: ActivityCategory.CULTURAL_EVENT,
    status: ActivityStatus.APPROVED,
    tags: [
      "Malouf",
      "Andalusian music",
      "live music",
      "cultural evening",
      "historical storytelling",
      "dinner",
    ],
  },

  // ── Fatma Ben Ali (index 1) ── Gastronomy
  {
    creatorId: 8,
    title: "Full-Day Medina Food Journey — Sfax",
    description:
      "An immersive full-day culinary journey through the winding alleys of Sfax's Medina. Visit hidden spice shops, meet family food artisans, and taste street food that guidebooks never mention. End the day cooking a traditional Sfaxian dinner in Fatma's family courtyard — dishes include fish couscous, stuffed octopus, and almond-filled baklava.",
    price: 85,
    date: new Date("2025-09-12T09:00:00Z"),
    location: "Sfax Medina",
    latitude: 34.7406,
    longitude: 10.7603,
    capacity: 8,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "food tour",
      "Sfax",
      "medina",
      "spice market",
      "couscous",
      "cooking class",
      "Tunisian cuisine",
    ],
  },
  {
    creatorId: 8,
    title: "Tunisian Pastry Masterclass — Sweets of Eid and Weddings",
    description:
      "Learn to make makroud, cornes de gazelle, and kaak warka — traditional Tunisian pastries prepared for celebrations and religious occasions. Fatma explains the symbolism behind each sweet, the regional variations across Tunisia, and the techniques passed through generations. Every participant goes home with a box of handmade sweets and the full recipe collection.",
    price: 60,
    date: new Date("2025-09-16T10:00:00Z"),
    location: "Sfax",
    latitude: 34.738,
    longitude: 10.762,
    capacity: 10,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "pastry",
      "makroud",
      "Tunisian sweets",
      "cooking class",
      "baking",
      "cultural food",
    ],
  },
  {
    creatorId: 8,
    title: "Harissa Making and the Spice Trade of Southern Tunisia",
    description:
      "Discover the fiery heart of Tunisian cuisine. Fatma leads a morning tour of Sfax's spice market, explaining the provenance and cultural significance of each ingredient, followed by a hands-on harissa-making session using stone-ground dried chilies, caraway, and garlic. Learn how harissa varies from region to region and its role in every Tunisian table.",
    price: 45,
    date: new Date("2025-09-18T09:30:00Z"),
    location: "Sfax",
    latitude: 34.739,
    longitude: 10.7615,
    capacity: 12,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "harissa",
      "spices",
      "cooking",
      "Tunisian food",
      "chili",
      "spice market",
      "hands-on",
    ],
  },

  // ── Youssef Trabelsi (index 2) ── Desert
  {
    creatorId: 9,
    title: "3-Day Sahara Camel Trek — Grand Erg Oriental",
    description:
      "A fully guided three-day camel trek through the Grand Erg Oriental, departing from Douz. Youssef navigates ancient caravan routes, stopping at hidden oases and Berber tent camps. Nights are spent under stars with no light pollution — astrophotography enthusiasts bring their cameras. Includes all meals, traditional Berber music by campfire, and morning sandboarding.",
    price: 280,
    date: new Date("2025-10-01T07:00:00Z"),
    location: "Douz, Kebili Governorate",
    latitude: 33.4571,
    longitude: 9.0186,
    capacity: 10,
    category: ActivityCategory.DESERT_EXPEDITION,
    status: ActivityStatus.APPROVED,
    tags: [
      "Sahara",
      "camel trek",
      "Grand Erg Oriental",
      "desert camping",
      "stargazing",
      "Berber culture",
      "sandboarding",
    ],
  },
  {
    creatorId: 9,
    title: "Desert Dawn Meditation and Sunrise Photography",
    description:
      "Wake before dawn and trek to a high dune ridge to witness the Saharan sunrise. Youssef guides a short desert survival workshop before the sun rises, then leads a silent observation session as the dunes turn gold. Perfect for photographers and anyone seeking a meditative desert experience away from the tourist crowds around Douz.",
    price: 40,
    date: new Date("2025-10-05T04:30:00Z"),
    location: "Douz, Kebili Governorate",
    latitude: 33.45,
    longitude: 9.025,
    capacity: 12,
    category: ActivityCategory.DESERT_EXPEDITION,
    status: ActivityStatus.APPROVED,
    tags: [
      "sunrise",
      "desert",
      "meditation",
      "photography",
      "dunes",
      "Sahara",
      "early morning",
    ],
  },
  {
    creatorId: 9,
    title: "Berber Star Stories — Sahara Night Sky Experience",
    description:
      "Far from any artificial light, Youssef leads a night sky experience rooted in Berber astronomical tradition. Learn how desert nomads navigated by stars, the Arabic names of constellations still used in modern astronomy, and the myths woven around them. Includes use of telescopes, traditional tea ceremony, and a Berber drum circle to close the night.",
    price: 50,
    date: new Date("2025-10-08T20:00:00Z"),
    location: "Douz, Kebili Governorate",
    latitude: 33.46,
    longitude: 9.018,
    capacity: 15,
    category: ActivityCategory.CULTURAL_EVENT,
    status: ActivityStatus.APPROVED,
    tags: [
      "stargazing",
      "astronomy",
      "Berber culture",
      "desert night",
      "telescope",
      "cultural storytelling",
    ],
  },

  // ── Leila Chaabane (index 3) ── Coastal / Marine
  {
    creatorId: 10,
    title: "Coral Reef Snorkeling Tour — Tabarka Marine Reserve",
    description:
      "Explore one of Tunisia's most biodiverse marine environments with a marine biologist as your guide. Leila identifies every species you encounter — nudibranchs, groupers, sea urchins, and occasional octopus. The tour includes a 20-minute pre-dive briefing on local marine ecosystems and a citizen science log where participants record their sightings.",
    price: 65,
    date: new Date("2025-08-20T09:00:00Z"),
    location: "Tabarka",
    latitude: 36.9544,
    longitude: 8.7587,
    capacity: 8,
    category: ActivityCategory.COASTAL_ESCAPE,
    status: ActivityStatus.APPROVED,
    tags: [
      "snorkeling",
      "coral reef",
      "marine biology",
      "Tabarka",
      "citizen science",
      "Mediterranean",
    ],
  },
  {
    creatorId: 10,
    title: "Freediving Introduction Course — Tabarka Bay",
    description:
      "A beginner-friendly two-day freediving course in the crystal-clear waters of Tabarka Bay. Leila covers breathing techniques, equalization, safety protocols, and underwater movement. By the end of day two, participants reach 10 meters on a single breath. Course includes all equipment, theory sessions, and a night snorkel on the second evening.",
    price: 120,
    date: new Date("2025-08-23T08:00:00Z"),
    location: "Tabarka",
    latitude: 36.952,
    longitude: 8.76,
    capacity: 6,
    category: ActivityCategory.COASTAL_ESCAPE,
    status: ActivityStatus.APPROVED,
    tags: [
      "freediving",
      "diving course",
      "beginner",
      "Tabarka",
      "underwater",
      "breathwork",
      "Mediterranean",
    ],
  },
  {
    creatorId: 10,
    title: "Underwater Photography Workshop — Posidonia Meadows",
    description:
      "A specialized workshop for photographers wanting to capture Tunisia's underwater landscapes. Leila leads participants through Tabarka's Posidonia seagrass meadows — a habitat critical for Mediterranean biodiversity. Covers camera settings for underwater shooting, composition techniques, and ethical wildlife photography. Max 4 participants for personalized coaching.",
    price: 95,
    date: new Date("2025-09-03T09:00:00Z"),
    location: "Tabarka",
    latitude: 36.953,
    longitude: 8.757,
    capacity: 4,
    category: ActivityCategory.COASTAL_ESCAPE,
    status: ActivityStatus.APPROVED,
    tags: [
      "underwater photography",
      "Posidonia",
      "marine ecosystem",
      "photography",
      "diving",
      "Mediterranean",
    ],
  },

  // ── Karim Gasmi (index 4) ── Art / Craft
  {
    creatorId: 11,
    title: "Zellige Mosaic Workshop — Sidi Bou Said",
    description:
      "Learn the ancient art of zellige tile-cutting in Karim's hilltop studio overlooking the Gulf of Tunis. Participants design and assemble a 30x30cm mosaic panel using traditional geometric patterns from Moroccan and Tunisian Islamic architecture. Karim provides historical context for each motif and its mathematical foundations. All materials provided; panels shipped home on request.",
    price: 70,
    date: new Date("2025-09-07T10:00:00Z"),
    location: "Sidi Bou Said",
    latitude: 36.8688,
    longitude: 10.3423,
    capacity: 8,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "zellige",
      "mosaic",
      "Islamic geometry",
      "Sidi Bou Said",
      "tile art",
      "workshop",
      "hands-on",
    ],
  },
  {
    creatorId: 11,
    title: "Open Studio — Contemporary Tunisian Painting",
    description:
      "Spend a full day in Karim's open studio in Sidi Bou Said exploring contemporary Tunisian painting. Karim introduces participants to the Tunis School of Fine Arts tradition, the influence of Paul Klee's visit to Tunisia in 1914, and current Tunisian contemporary artists. Participants work on their own canvas using acrylic and mixed media under Karim's mentorship.",
    price: 80,
    date: new Date("2025-09-13T10:00:00Z"),
    location: "Sidi Bou Said",
    latitude: 36.87,
    longitude: 10.3415,
    capacity: 10,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "painting",
      "open studio",
      "contemporary art",
      "Tunis School",
      "Sidi Bou Said",
      "mixed media",
    ],
  },
  {
    creatorId: 11,
    title: "Ceramics and Pottery Afternoon — North African Glazing Traditions",
    description:
      "A half-day ceramics session focusing on traditional North African hand-building and surface decoration. Karim demonstrates coiling, burnishing, and the application of copper and manganese oxides used in traditional Nabeul pottery. Participants create a small bowl or cup and apply their own glaze design. Kiln-fired pieces shipped within two weeks.",
    price: 55,
    date: new Date("2025-09-21T14:00:00Z"),
    location: "Sidi Bou Said",
    latitude: 36.8695,
    longitude: 10.343,
    capacity: 10,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "ceramics",
      "pottery",
      "glazing",
      "Nabeul tradition",
      "hand-building",
      "North African crafts",
    ],
  },

  // ── Nadia Khelifa (index 5) ── Wellness
  {
    creatorId: 12,
    title: "Traditional Tunisian Hammam Ritual — La Marsa",
    description:
      "A full traditional hammam experience at a historic neighborhood bathhouse in La Marsa, guided by Nadia. Includes a full-body kessa exfoliation with black soap, a rhassoul clay mask, and a rose water rinse. Nadia explains the social and spiritual significance of the hammam in Tunisian culture and shares the history of the specific bathhouse. Appropriate for all genders.",
    price: 50,
    date: new Date("2025-09-08T10:00:00Z"),
    location: "La Marsa, Tunis",
    latitude: 36.8883,
    longitude: 10.3236,
    capacity: 6,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "hammam",
      "wellness",
      "kessa",
      "black soap",
      "Tunisian tradition",
      "La Marsa",
      "self-care",
    ],
  },
  {
    creatorId: 12,
    title: "Natural Beauty and Herbal Remedies Workshop",
    description:
      "Nadia shares the traditional Tunisian knowledge of medicinal plants and natural beauty ingredients found in local markets. Participants blend their own body oil using argan, prickly pear seed oil, and jasmine absolute, and prepare a harqous (kohl) eyeline mixture as practiced for centuries. A visit to the local herb market precedes the workshop.",
    price: 45,
    date: new Date("2025-09-15T10:00:00Z"),
    location: "La Marsa, Tunis",
    latitude: 36.8875,
    longitude: 10.322,
    capacity: 10,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "natural beauty",
      "herbal remedies",
      "argan oil",
      "traditional medicine",
      "wellness workshop",
    ],
  },
  {
    creatorId: 12,
    title: "Jasmine Harvest and Aromatherapy Morning — La Marsa",
    description:
      "Join Nadia on an early morning walk through La Marsa's jasmine gardens during peak bloom season. Learn to harvest flowers correctly, then distill your own small vial of jasmine hydrosol using a traditional copper alembic still. The session closes with a guided aromatherapy relaxation practice and a tasting of jasmine-infused tea and pastries.",
    price: 60,
    date: new Date("2025-09-19T07:00:00Z"),
    location: "La Marsa, Tunis",
    latitude: 36.889,
    longitude: 10.324,
    capacity: 8,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "jasmine",
      "aromatherapy",
      "distillation",
      "harvest",
      "wellness",
      "sensory experience",
    ],
  },

  // ── Omar Ben Youssef (index 6) ── History / Archaeology
  {
    creatorId: 13,
    title: "Carthage Beyond the Guidebook — Expert Archaeological Tour",
    description:
      "A 4-hour deep-dive archaeological tour of Carthage led by Omar, a professional archaeologist who has worked on-site excavations. Visitors access areas not open to general public, examine original Punic artifacts up close, and hear the unfiltered story of Carthage's rise, its conflict with Rome, and the myths that distort popular history. Includes Omar's own illustrated field notes.",
    price: 90,
    date: new Date("2025-09-11T09:00:00Z"),
    location: "Carthage, Tunis",
    latitude: 36.8528,
    longitude: 10.3233,
    capacity: 8,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Carthage",
      "archaeology",
      "Punic history",
      "Roman history",
      "expert tour",
      "ancient sites",
    ],
  },
  {
    creatorId: 13,
    title: "Dougga Roman City — Full Day Archaeological Immersion",
    description:
      "A full-day visit to Dougga, Tunisia's best-preserved Roman city and a UNESCO World Heritage Site. Omar guides visitors through the Capitol, the theater, the thermal baths, and the Libyan-Punic mausoleum, decoding the Latin inscriptions, architectural evolution, and daily life of Roman North Africa. Includes a picnic lunch among the ruins and a sunset viewing from the hilltop theater.",
    price: 110,
    date: new Date("2025-09-25T08:00:00Z"),
    location: "Dougga, Beja Governorate",
    latitude: 36.422,
    longitude: 9.2186,
    capacity: 10,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Dougga",
      "Roman ruins",
      "UNESCO",
      "archaeology",
      "North Africa",
      "historical tour",
      "Latin inscriptions",
    ],
  },
  {
    creatorId: 13,
    title: "El Jem Amphitheater — Behind-the-Scenes Archaeologist Visit",
    description:
      "Go beyond the standard tourist visit to El Jem's Roman amphitheater — the third largest in the world — with an archaeologist who knows every tunnel and chamber. Omar accesses underground galleries, explains gladiatorial combat culture, discusses the economic history of Roman Thysdrus, and shares ongoing excavation findings from the surrounding area. Ends with a visit to the El Jem archaeological museum.",
    price: 95,
    date: new Date("2025-10-10T09:00:00Z"),
    location: "El Jem, Mahdia Governorate",
    latitude: 35.2963,
    longitude: 10.7075,
    capacity: 8,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "El Jem",
      "Roman amphitheater",
      "gladiators",
      "archaeology",
      "underground tour",
      "ancient Rome",
    ],
  },

  // ── Amira Bouzid (index 7) ── Textile / Berber crafts
  {
    creatorId: 14,
    title: "Berber Carpet Weaving Workshop — Gafsa",
    description:
      "Spend a full day learning traditional Berber carpet weaving at Amira's cooperative in Gafsa. Using a traditional horizontal loom, participants weave a 20x30cm kilim panel while Amira decodes the symbolic language of each geometric motif — triangles representing feminine power, diamonds signifying protection, and zigzag lines encoding migration routes. Natural wool is dyed with local plants on-site.",
    price: 75,
    date: new Date("2025-10-02T09:00:00Z"),
    location: "Gafsa",
    latitude: 34.425,
    longitude: 8.7842,
    capacity: 8,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "Berber weaving",
      "kilim",
      "carpet",
      "loom",
      "natural dye",
      "Gafsa",
      "textile art",
      "women's cooperative",
    ],
  },
  {
    creatorId: 14,
    title:
      "Natural Dye Workshop — Plants, Minerals, and Berber Color Knowledge",
    description:
      "Amira leads a morning workshop extracting natural dyes from plants and minerals collected in the Gafsa region: pomegranate peel for ochre, indigo for deep blues, henna for warm reds, and saffron for gold. Participants mordant and dye wool skeins using traditional methods unchanged for centuries. Covers the trade history of natural pigments across the Sahara and Mediterranean.",
    price: 50,
    date: new Date("2025-10-06T09:30:00Z"),
    location: "Gafsa",
    latitude: 34.428,
    longitude: 8.782,
    capacity: 10,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "natural dye",
      "indigo",
      "henna",
      "Berber craft",
      "wool",
      "plant pigments",
      "textile workshop",
    ],
  },
  {
    creatorId: 14,
    title: "Embroidery and the Language of Tunisian Wedding Textiles",
    description:
      "Amira unfolds ceremonial wedding textiles from her private collection — garments embroidered with silver and gold thread from Gafsa, Nabeul, and Mahdia — and explains the story each one tells about the bride's family, region, and status. Participants then practice traditional Tunisian cross-stitch embroidery on a linen sampler, guided by Amira through each stitch and its symbolic meaning.",
    price: 65,
    date: new Date("2025-10-09T10:00:00Z"),
    location: "Gafsa",
    latitude: 34.426,
    longitude: 8.785,
    capacity: 10,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "embroidery",
      "wedding textiles",
      "Tunisian craft",
      "silver thread",
      "textile history",
      "cross-stitch",
    ],
  },

  // ── Mixed additional activities spread across creators ──
  {
    creatorId: 7,
    title: "Bardo Museum Deep Dive — Roman Mosaic Masterpieces",
    description:
      "A guided 3-hour expert tour of the Bardo National Museum's unparalleled Roman mosaic collection — the largest in the world. Sami connects each mosaic narrative to the literary works of Virgil, Ovid, and Homer, bringing mythological scenes alive with storytelling. Includes the rarely visited Byzantine gallery and a quiet session sketching mosaic details in the museum garden.",
    price: 55,
    date: new Date("2025-09-22T10:00:00Z"),
    location: "Tunis",
    latitude: 36.8173,
    longitude: 10.1337,
    capacity: 10,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "Bardo Museum",
      "Roman mosaics",
      "Tunis",
      "museum tour",
      "mythology",
      "UNESCO",
      "Byzantine art",
    ],
  },
  {
    creatorId: 8,
    title: "Farm-to-Table Olive Oil Experience — Cap Bon",
    description:
      "Visit an artisanal olive farm in Cap Bon during the autumn harvest, participate in hand-picking and cold-pressing olives, and taste oils ranging from delicate Chemlali to robust Chemchali varieties alongside Tunisian bread, tomatoes, and herbs. The farmer explains Tunisia's history as the olive breadbasket of Rome and the role of olive oil in modern Tunisian export economy.",
    price: 70,
    date: new Date("2025-11-05T09:00:00Z"),
    location: "Cap Bon, Nabeul Governorate",
    latitude: 36.7303,
    longitude: 10.8,
    capacity: 12,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "olive oil",
      "farm visit",
      "Cap Bon",
      "harvest",
      "Tunisian agriculture",
      "food culture",
      "tasting",
    ],
  },
  {
    creatorId: 9,
    title: "Chott el-Djerid Salt Lake Sunrise Drive",
    description:
      "Drive across the vast Chott el-Djerid — the largest salt lake in the Sahara — at dawn when the surface becomes a mirror of the sky. Youssef stops at key vantage points, explains the lake's hydrology, the optical illusions that create mirages, and the traditional salt harvesting culture of the region. Includes a short walk on the lake's crust where safe and a desert breakfast.",
    price: 60,
    date: new Date("2025-10-15T05:00:00Z"),
    location: "Chott el-Djerid, Tozeur Governorate",
    latitude: 33.7,
    longitude: 8.43,
    capacity: 8,
    category: ActivityCategory.NATURE_ADVENTURE,
    status: ActivityStatus.APPROVED,
    tags: [
      "Chott el-Djerid",
      "salt lake",
      "desert",
      "sunrise",
      "mirage",
      "nature",
      "Sahara",
    ],
  },
  {
    creatorId: 10,
    title: "Kayaking the Ichkeul Lake — Wetland Birdwatching",
    description:
      "Paddle through the Ichkeul National Park, a UNESCO-listed wetland hosting tens of thousands of migratory birds each winter. Leila guides participants by kayak through reed beds and shallow lagoons, identifying flamingos, spoonbills, and marsh harriers. The morning ends at the Ichkeul mountain for a hike with panoramic views and a packed Tunisian picnic.",
    price: 55,
    date: new Date("2025-11-20T07:30:00Z"),
    location: "Ichkeul National Park, Bizerte",
    latitude: 37.16,
    longitude: 9.67,
    capacity: 10,
    category: ActivityCategory.NATURE_ADVENTURE,
    status: ActivityStatus.APPROVED,
    tags: [
      "kayaking",
      "Ichkeul",
      "birdwatching",
      "wetlands",
      "flamingo",
      "UNESCO",
      "eco-tour",
    ],
  },
  {
    creatorId: 11,
    title: "Street Art and Graffiti Tour — Tunis City Walls",
    description:
      "Karim leads a walking tour of Tunis neighborhoods where street art has transformed crumbling walls into political and cultural statements. From El Menzah murals protesting social inequality to the Avenue Habib Bourguiba graffiti that documented the 2011 revolution, each work is placed in its historical and artistic context. Includes a live spray-paint demonstration and a discussion with a local graffiti artist.",
    price: 40,
    date: new Date("2025-09-17T16:00:00Z"),
    location: "Tunis",
    latitude: 36.8065,
    longitude: 10.1815,
    capacity: 15,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "street art",
      "graffiti",
      "Tunis",
      "urban art",
      "political art",
      "2011 revolution",
      "contemporary culture",
    ],
  },
  {
    creatorId: 12,
    title: "Sunset Yoga and Meditation on Sidi Bou Said Cliff",
    description:
      "A 90-minute outdoor yoga and breathwork session on the whitewashed cliff-edge terrace overlooking the Gulf of Tunis, as the sun sets behind the island of Zembra. Nadia combines Hatha yoga sequences with traditional Tunisian breathing techniques from Sufi practice. Participants receive a small bottle of local jasmine oil and wild rosemary to take home.",
    price: 35,
    date: new Date("2025-09-23T17:30:00Z"),
    location: "Sidi Bou Said",
    latitude: 36.8688,
    longitude: 10.343,
    capacity: 12,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "yoga",
      "sunset",
      "Sidi Bou Said",
      "meditation",
      "breathwork",
      "wellness",
      "cliff",
    ],
  },
  {
    creatorId: 13,
    title: "Numismatic Journey — Ancient Coins of Carthage and Roman Africa",
    description:
      "Omar presents his personal collection of authenticated Punic, Numidian, and Roman coins minted in ancient Tunisia, tracing the political economy from the silver Carthaginian shekel to the imperial Roman denarius. Participants use jeweler's loupes to examine coins, discuss minting techniques, and identify deities and rulers. A rare opportunity for history and numismatics enthusiasts.",
    price: 45,
    date: new Date("2025-10-03T15:00:00Z"),
    location: "Carthage, Tunis",
    latitude: 36.853,
    longitude: 10.324,
    capacity: 8,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "numismatics",
      "ancient coins",
      "Carthage",
      "Roman",
      "Punic",
      "history",
      "collector",
    ],
  },
  {
    creatorId: 14,
    title: "Nabeul Ceramics Market and Pottery Village Tour",
    description:
      "Visit the ceramics capital of Tunisia — Nabeul — with Amira as guide through family-run ateliers producing the region's signature cobalt-and-white patterns. Watch master potters throw on foot-pedal wheels, observe wood-fired kilns, and understand the difference between tourist imports and authentic Nabeul production. Includes a bargaining masterclass at the weekly Friday market.",
    price: 50,
    date: new Date("2025-10-17T09:00:00Z"),
    location: "Nabeul, Cap Bon",
    latitude: 36.4561,
    longitude: 10.7376,
    capacity: 12,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "Nabeul",
      "ceramics",
      "pottery",
      "Cap Bon",
      "market",
      "craft village",
      "cobalt blue",
    ],
  },
  {
    creatorId: 7,
    title: "Jewish Heritage Walk — La Goulette and the Hara",
    description:
      "A walking tour of the former Jewish Quarter of Tunis — the Hara — and the historic port town of La Goulette, tracing 2,500 years of Jewish presence in Tunisia. Sami visits synagogues, cemeteries, and family-run shops still operating under Jewish ownership, sharing personal stories from community elders and the Sephardic cultural legacy still alive in Tunisian cuisine and music.",
    price: 45,
    date: new Date("2025-09-26T09:00:00Z"),
    location: "La Goulette, Tunis",
    latitude: 36.8197,
    longitude: 10.3049,
    capacity: 10,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Jewish heritage",
      "Sephardic culture",
      "La Goulette",
      "Tunis history",
      "walking tour",
      "synagogue",
    ],
  },
  {
    creatorId: 9,
    title: "Tataouine Ksour Trek — Berber Fortified Granaries",
    description:
      "A one-day trekking tour through the dramatic landscape around Tataouine, visiting a series of ancient ksar (fortified Berber granary villages) perched on hilltops. Youssef leads the route through Ksar Ouled Soltane, Ksar Hadada, and lesser-known sites, explaining the architecture, clan history, and the reason Star Wars filmmakers chose this landscape for Tatooine.",
    price: 80,
    date: new Date("2025-11-01T08:00:00Z"),
    location: "Tataouine Governorate",
    latitude: 32.9297,
    longitude: 10.45,
    capacity: 10,
    category: ActivityCategory.NATURE_ADVENTURE,
    status: ActivityStatus.APPROVED,
    tags: [
      "Tataouine",
      "ksar",
      "Berber architecture",
      "trekking",
      "Star Wars",
      "desert",
      "historical walk",
    ],
  },
  {
    creatorId: 10,
    title: "Night Sailing and Phosphorescence — Tabarka Bay",
    description:
      "Sail out from Tabarka port at sunset on a traditional wooden fishing boat, then anchor in a quiet bay after dark. Leila leads participants into the water to experience bioluminescent plankton — a rare nighttime phenomenon that turns every movement into streaks of blue light. Includes safety briefing, cold drinks, and a midnight return to port under the stars.",
    price: 70,
    date: new Date("2025-08-28T19:00:00Z"),
    location: "Tabarka",
    latitude: 36.955,
    longitude: 8.756,
    capacity: 8,
    category: ActivityCategory.COASTAL_ESCAPE,
    status: ActivityStatus.APPROVED,
    tags: [
      "sailing",
      "bioluminescence",
      "night swim",
      "Tabarka",
      "Mediterranean",
      "phosphorescence",
      "boat",
    ],
  },
  {
    creatorId: 11,
    title: "Henna Art and Body Decoration Workshop",
    description:
      "Karim invites a master henna artist to lead a workshop on the traditional art of henna body decoration as practiced in Tunisian weddings and celebrations. Participants learn the regional differences between northern and southern Tunisian patterns, the symbolism of specific motifs, and practice on each other's hands. Natural henna paste is prepared on-site from dried leaves.",
    price: 40,
    date: new Date("2025-09-28T14:00:00Z"),
    location: "Sidi Bou Said",
    latitude: 36.8688,
    longitude: 10.3423,
    capacity: 12,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "henna",
      "body art",
      "Tunisian tradition",
      "wedding culture",
      "workshop",
      "natural pigments",
    ],
  },
  {
    creatorId: 12,
    title: "Thalassotherapy and Sea Salt Ritual — Hammamet",
    description:
      "A 3-hour therapeutic sea experience using thalassotherapy techniques rooted in Tunisian coastal healing traditions. Nadia combines warm seawater immersion with mineral-rich sea salt body scrubs, seaweed wraps, and a guided relaxation session on the beach. The program draws on the ancient Greek and Arab understanding of the sea as medicine.",
    price: 80,
    date: new Date("2025-10-12T10:00:00Z"),
    location: "Hammamet, Nabeul Governorate",
    latitude: 36.3997,
    longitude: 10.5529,
    capacity: 6,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "thalassotherapy",
      "sea salt",
      "Hammamet",
      "coastal wellness",
      "seaweed wrap",
      "Mediterranean healing",
    ],
  },
  {
    creatorId: 13,
    title: "Sbeitla Roman Temples — Forgotten City of Byzantine Africa",
    description:
      "An off-the-beaten-path full-day visit to Sbeitla, one of Tunisia's least-visited but most spectacular Roman sites, featuring three intact Capitol temples dedicated to Jupiter, Juno, and Minerva. Omar uncovers the site's pivotal role in the Arab conquest of North Africa in 647 AD — the moment ancient Rome gave way to the Islamic era. Includes a traditional lunch at a local farmhouse.",
    price: 100,
    date: new Date("2025-10-20T08:00:00Z"),
    location: "Sbeitla, Kasserine Governorate",
    latitude: 35.2378,
    longitude: 9.1214,
    capacity: 10,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Sbeitla",
      "Roman temples",
      "Byzantine Africa",
      "Arab conquest",
      "archaeology",
      "off-the-beaten-path",
    ],
  },
  {
    creatorId: 14,
    title: "Visit a Women's Weaving Cooperative — Southern Tunisia",
    description:
      "Amira leads a visit to a women-run weaving cooperative in a village outside Gafsa, where traditional Berber carpet production sustains an entire community. Meet the weavers, see the wool spinning process from raw fleece to finished thread, and hear their stories about preserving craft traditions across generations. A portion of every purchase goes directly to cooperative funds.",
    price: 40,
    date: new Date("2025-10-23T09:30:00Z"),
    location: "Gafsa",
    latitude: 34.42,
    longitude: 8.79,
    capacity: 12,
    category: ActivityCategory.CULTURAL_EVENT,
    status: ActivityStatus.APPROVED,
    tags: [
      "women's cooperative",
      "weaving",
      "Berber craft",
      "community tourism",
      "wool",
      "social enterprise",
    ],
  },
  {
    creatorId: 7,
    title: "Tunisian Breakfast Ritual — A Morning Food Cultural Journey",
    description:
      "Fatma invites a small group to experience a traditional Tunisian breakfast in its full cultural context: slata mechouia, fricassee, lablebi soup, and fresh khoubz bread baked in a wood-fired oven. She explains the regional variations of breakfast across Tunisia — what people eat in Djerba versus Bizerte versus Tunis — and the role of the coffee shop in Tunisian social life.",
    price: 30,
    date: new Date("2025-09-06T08:00:00Z"),
    location: "Sfax",
    latitude: 34.7406,
    longitude: 10.76,
    capacity: 10,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "breakfast",
      "Tunisian food",
      "lablebi",
      "fricassee",
      "cultural meal",
      "food ritual",
      "morning",
    ],
  },
  {
    creatorId: 8,
    title: "Djerba Seafood Trail — Island Flavors and Fishermen",
    description:
      "A guided half-day food tour through Houmt Souk's fish market and the fishing village of Ajim on the Djerba coast. Fatma leads the group through the morning catch inspection, explains how island residents prepare octopus in chermoula and salt-cured mullet roe (poutargue), and ends with a shared seafood lunch cooked over charcoal at a fisherman's courtyard. Djerba's cuisine is unlike anywhere else in Tunisia.",
    price: 65,
    date: new Date("2025-10-28T08:00:00Z"),
    location: "Djerba, Médenine Governorate",
    latitude: 33.8755,
    longitude: 10.8597,
    capacity: 10,
    category: ActivityCategory.GASTRONOMY,
    status: ActivityStatus.APPROVED,
    tags: [
      "Djerba",
      "seafood",
      "fish market",
      "poutargue",
      "island food",
      "fishermen",
      "octopus",
    ],
  },
  {
    creatorId: 9,
    title: "Oasis Permaculture Walk — Date Palm Agriculture of Tozeur",
    description:
      "A guided morning walk through Tozeur's ancient oasis irrigation system, one of the most sophisticated in the Arab world. Youssef explains the 1,000-year-old foggara water channels, the three-layer agriculture system (date palms, fruit trees, vegetables), and the varieties of dates grown in the region — from Deglet Nour to Allig. Includes a date tasting session with 12 varieties and a visit to a traditional date press.",
    price: 45,
    date: new Date("2025-10-18T08:30:00Z"),
    location: "Tozeur Oasis",
    latitude: 33.9197,
    longitude: 8.136,
    capacity: 12,
    category: ActivityCategory.NATURE_ADVENTURE,
    status: ActivityStatus.APPROVED,
    tags: [
      "oasis",
      "Tozeur",
      "date palms",
      "permaculture",
      "irrigation",
      "sustainable agriculture",
      "dates",
    ],
  },
  {
    creatorId: 10,
    title: "Cap Blanc Coastal Hike — Northernmost Point of Africa",
    description:
      "A 12km guided coastal hike along the dramatic cliffs of Cap Blanc — the northernmost point of the African continent — with Leila providing ecological commentary on the Mediterranean scrubland, cliff-nesting seabirds, and endemic plants visible along the route. The trail ends at the cape lighthouse with a panoramic view across to Sicily on clear days. Swim stop at a hidden rocky cove included.",
    price: 40,
    date: new Date("2025-09-27T08:00:00Z"),
    location: "Cap Blanc, Bizerte Governorate",
    latitude: 37.549,
    longitude: 9.964,
    capacity: 10,
    category: ActivityCategory.NATURE_ADVENTURE,
    status: ActivityStatus.APPROVED,
    tags: [
      "Cap Blanc",
      "coastal hike",
      "northernmost Africa",
      "cliffs",
      "Mediterranean",
      "birdwatching",
      "lighthouse",
    ],
  },
  {
    creatorId: 11,
    title: "Independent Bookshop Tour and Literary Tunis Walk",
    description:
      "A walking tour of Tunis's surviving independent bookshops, literary cafés, and the cultural institutions that make the capital a quietly vibrant book city. Karim visits four independent booksellers including the legendary Librairie Scriptorium on Rue de Rome, Fnac Tunis, and a used book market off Avenue Bourguiba. The tour ends with a reading from contemporary Tunisian authors at a cultural center.",
    price: 25,
    date: new Date("2025-09-24T15:00:00Z"),
    location: "Tunis City Centre",
    latitude: 36.802,
    longitude: 10.1798,
    capacity: 15,
    category: ActivityCategory.CULTURAL_EVENT,
    status: ActivityStatus.APPROVED,
    tags: [
      "bookshops",
      "literary culture",
      "Tunis",
      "reading",
      "independent culture",
      "walking tour",
      "contemporary literature",
    ],
  },
  {
    creatorId: 12,
    title: "Sound Bath and Sufi Breathing — Inner Silence Retreat",
    description:
      "A 2-hour inner silence session in a whitewashed riad in La Marsa, drawing on Tunisian Sufi breathing and vocal traditions alongside modern sound healing using Tibetan bowls and a frame drum. Nadia opens with a traditional hadra rhythm sequence before guiding participants into deep relaxation. Designed for travelers experiencing burnout or seeking genuine stillness. Limited to 6 people for intimacy.",
    price: 55,
    date: new Date("2025-10-07T18:00:00Z"),
    location: "La Marsa, Tunis",
    latitude: 36.8885,
    longitude: 10.3225,
    capacity: 6,
    category: ActivityCategory.WELLNESS,
    status: ActivityStatus.APPROVED,
    tags: [
      "sound bath",
      "Sufi breathing",
      "meditation",
      "La Marsa",
      "silence retreat",
      "hadra",
      "relaxation",
    ],
  },
  {
    creatorId: 13,
    title: "Kairouan — Holy City Pilgrimage and Sacred Architecture",
    description:
      "A full-day expert visit to Kairouan, the fourth holiest city in Islam and a UNESCO World Heritage site. Omar leads an in-depth tour of the Great Mosque of Okba Ibn Nafaa (founded 670 AD), the Mosque of the Three Doors, the Aghlabid Basins, and the city's historic religious schools. Includes access to areas restricted to general visitors and a private briefing with the mosque's resident historian.",
    price: 105,
    date: new Date("2025-10-14T08:00:00Z"),
    location: "Kairouan",
    latitude: 35.6833,
    longitude: 10.096,
    capacity: 8,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Kairouan",
      "Islamic architecture",
      "holy city",
      "mosque",
      "UNESCO",
      "Aghlabid",
      "pilgrimage",
    ],
  },
  {
    creatorId: 14,
    title: "Silver Jewelry and Berber Amulet Workshop — Tozeur",
    description:
      "A workshop led by a silversmith from Amira's cooperative network in Tozeur, specializing in traditional Berber protective amulets — the khamsa, the crescent and star, and the fish — worked in silver wire and embellished with coral and amber beads. Participants learn basic wire-wrapping techniques and create their own pendant necklace. The historical and spiritual meaning behind each symbol is explained throughout.",
    price: 70,
    date: new Date("2025-10-26T10:00:00Z"),
    location: "Tozeur",
    latitude: 33.9197,
    longitude: 8.134,
    capacity: 8,
    category: ActivityCategory.ARTISAN_WORKSHOP,
    status: ActivityStatus.APPROVED,
    tags: [
      "silver jewelry",
      "Berber amulet",
      "khamsa",
      "wire wrapping",
      "traditional jewelry",
      "Tozeur",
      "craft workshop",
    ],
  },
  {
    creatorId: 10,
    title: "Biological Marine Reserve — Galite Island Day Trip",
    description:
      "A full-day boat excursion to La Galite — a remote uninhabited island 60km off the Tabarka coast, one of Tunisia's few designated marine protected areas. Leila leads snorkeling sessions over pristine rocky reefs and explains the island's status as a critical habitat for Mediterranean monk seals. Includes a surface interval on the island's pebble beach, packed lunch, and a marine biology Q&A session on the return crossing.",
    price: 150,
    date: new Date("2025-09-06T06:30:00Z"),
    location: "La Galite Island (departure: Tabarka)",
    latitude: 37.522,
    longitude: 8.932,
    capacity: 8,
    category: ActivityCategory.COASTAL_ESCAPE,
    status: ActivityStatus.APPROVED,
    tags: [
      "La Galite",
      "marine reserve",
      "monk seal",
      "snorkeling",
      "remote island",
      "boat trip",
      "conservation",
    ],
  },
  {
    creatorId: 9,
    title: "Matmata Underground Troglodyte Village — Desert Architecture Walk",
    description:
      "A guided exploration of Matmata's extraordinary underground troglodyte dwellings — pit houses carved 10 meters into the earth to maintain constant temperature against the Saharan heat. Youssef visits both inhabited homes still used by Berber families today and the famous Hotel Sidi Driss (used as Luke Skywalker's home in Star Wars IV). Explains the spatial logic, social history, and engineering ingenuity behind this unique desert architecture.",
    price: 55,
    date: new Date("2025-11-08T09:00:00Z"),
    location: "Matmata, Gabes Governorate",
    latitude: 33.543,
    longitude: 9.972,
    capacity: 12,
    category: ActivityCategory.HISTORICAL_TOUR,
    status: ActivityStatus.APPROVED,
    tags: [
      "Matmata",
      "troglodyte",
      "underground houses",
      "Berber architecture",
      "Star Wars",
      "desert",
      "cultural heritage",
    ],
  },
  {
    creatorId: 7,
    title: "Zitouna Mosque and Islamic Tunis — Architecture and Spirituality",
    description:
      "A morning focused on the spiritual heart of Tunis — the Great Mosque of Zitouna, founded in 698 AD. Sami walks participants through the mosque's architectural evolution over 13 centuries, its role as the Arab world's oldest university, and the Quranic schools still operating in the surrounding medina. Respectful visits to active zaouias (Sufi lodges) are included for those interested.",
    price: 40,
    date: new Date("2025-09-29T09:00:00Z"),
    location: "Medina of Tunis",
    latitude: 36.7988,
    longitude: 10.1701,
    capacity: 10,
    category: ActivityCategory.ART_HERITAGE,
    status: ActivityStatus.APPROVED,
    tags: [
      "Zitouna Mosque",
      "Islamic architecture",
      "Sufi",
      "medina",
      "spiritual tour",
      "history",
      "religious culture",
    ],
  },
];

// ─── PLACES (30) ─────────────────────────────────────────────────────────────

const placesData = [
  // ── RESTAURANTS ──
  {
    name: "Dar El Jeld",
    category: PlaceCategory.RESTAURANT,
    address: "5 Rue Dar El Jeld, Medina",
    city: "Tunis",
    latitude: 36.799,
    longitude: 10.17,
    rating: 4.8,
    reviewCount: 1243,
    tags: [
      "traditional Tunisian",
      "fine dining",
      "Medina",
      "couscous",
      "tajine",
      "historic riad",
    ],
    description:
      "One of Tunis's most celebrated traditional restaurants, housed in a magnificently restored 18th-century palace in the heart of the Medina. The menu showcases the full range of classical Tunisian cuisine — brik, couscous with lamb and dried vegetables, and slow-cooked tajines — in an atmosphere of carved plaster and mosaic tile.",
  },
  {
    name: "Essaada Restaurant",
    category: PlaceCategory.RESTAURANT,
    address: "Avenue Bourguiba, Sfax Centre",
    city: "Sfax",
    latitude: 34.739,
    longitude: 10.76,
    rating: 4.5,
    reviewCount: 678,
    tags: [
      "Sfax cuisine",
      "fish couscous",
      "octopus",
      "local institution",
      "Tunisian seafood",
    ],
    description:
      "An unpretentious local institution in central Sfax, famous for its definitive fish couscous and grilled octopus. Frequented exclusively by Sfaxians who know it as the most honest representation of the city's distinct culinary identity — simpler, spicier, and more sea-forward than Tunis cuisine.",
  },
  {
    name: "Le Fondouk",
    category: PlaceCategory.RESTAURANT,
    address: "Sidi Bou Said Village, Route de la Corniche",
    city: "Sidi Bou Said",
    latitude: 36.8695,
    longitude: 10.3425,
    rating: 4.6,
    reviewCount: 892,
    tags: [
      "Mediterranean",
      "seafood",
      "rooftop",
      "Sidi Bou Said",
      "Gulf of Tunis view",
      "romantic",
    ],
    description:
      "A rooftop terrace restaurant perched above the blue-and-white village of Sidi Bou Said, with sweeping views over the Gulf of Tunis. Serves a contemporary Mediterranean menu drawing on Tunisian, French, and Italian influences, with a focus on fresh daily-caught fish and seasonal vegetables from nearby farms.",
  },
  {
    name: "Restaurant Chez Slah",
    category: PlaceCategory.RESTAURANT,
    address: "Rue Pierre Coubertin, La Marsa",
    city: "La Marsa",
    latitude: 36.888,
    longitude: 10.323,
    rating: 4.4,
    reviewCount: 540,
    tags: [
      "family restaurant",
      "La Marsa",
      "grilled fish",
      "brik",
      "budget friendly",
      "locals favorite",
    ],
    description:
      "A beloved family-run restaurant in La Marsa, operating for over 40 years. The menu is short, the quality consistent, and the prices reasonable — grilled sea bass, tuna brik, and hearty chorba soup remain the perennial favourites. Often full by 1pm on weekdays — arrive early.",
  },
  {
    name: "Nomad Desert Kitchen",
    category: PlaceCategory.RESTAURANT,
    address: "Route de Tozeur, Douz",
    city: "Douz",
    latitude: 33.459,
    longitude: 9.02,
    rating: 4.3,
    reviewCount: 312,
    tags: [
      "desert food",
      "Berber cuisine",
      "Douz",
      "lamb",
      "tagine",
      "oasis cooking",
    ],
    description:
      "A small open-air restaurant in Douz run by a Bedouin family, serving traditional southern Tunisian dishes cooked over charcoal and wood. Specialties include slow-roasted lamb in an underground earth oven, Berber-style vegetable tagine, and date pastries. Meals are served on low cushions around communal tables.",
  },

  // ── CAFES ──
  {
    name: "Café Sidi Chabaane",
    category: PlaceCategory.CAFE,
    address: "Sidi Bou Said Cliff, Route de la Corniche",
    city: "Sidi Bou Said",
    latitude: 36.87,
    longitude: 10.344,
    rating: 4.7,
    reviewCount: 2105,
    tags: [
      "iconic cafe",
      "Gulf of Tunis view",
      "pine nuts coffee",
      "sunset",
      "Sidi Bou Said",
      "historic",
    ],
    description:
      "Arguably the most famous café in Tunisia, perched on the cliff edge of Sidi Bou Said with an unobstructed view across the Gulf of Tunis to the Cap Bon peninsula. The café's signature drink — qahwa au pignons, dark Arabic coffee topped with toasted pine nuts — has been served here since 1914. Arrive at sunset for one of the Mediterranean's most celebrated views.",
  },
  {
    name: "M'rabet Café",
    category: PlaceCategory.CAFE,
    address: "Souk Et-Trouk, Medina",
    city: "Tunis",
    latitude: 36.7985,
    longitude: 10.169,
    rating: 4.5,
    reviewCount: 879,
    tags: [
      "Medina",
      "traditional café",
      "hookah",
      "mint tea",
      "live music",
      "historic building",
    ],
    description:
      "A centuries-old café built above an ancient mosque in the heart of the Tunis Medina souk. One of the few remaining traditional Tunisian cafés where old men play dominoes, hookah smoke drifts through arched colonnades, and mint tea is served in small glasses with a cube of sugar. Occasional live Malouf music on Thursday evenings.",
  },
  {
    name: "Café de Paris",
    category: PlaceCategory.CAFE,
    address: "Place de l'Indépendance, Avenue Bourguiba",
    city: "Tunis",
    latitude: 36.7992,
    longitude: 10.1826,
    rating: 4.2,
    reviewCount: 1456,
    tags: [
      "colonial architecture",
      "Avenue Bourguiba",
      "espresso",
      "people watching",
      "historic",
      "terrace",
    ],
    description:
      "An elegant French-colonial era café on the main artery of Avenue Bourguiba, with marble tables and a wide terrace perfect for watching Tunisian city life. Serves Italian espresso, fresh-squeezed juices, and a light menu of pastries and sandwiches. A historic landmark that has hosted journalists, artists, and politicians since the 1920s.",
  },
  {
    name: "Diar Lemdina Café",
    category: PlaceCategory.CAFE,
    address: "Rue de la Kasbah, Medina",
    city: "Tunis",
    latitude: 36.7998,
    longitude: 10.168,
    rating: 4.4,
    reviewCount: 445,
    tags: [
      "riad café",
      "medina",
      "courtyard",
      "artisanal coffee",
      "quiet",
      "boutique",
    ],
    description:
      "A small boutique café in a restored Medina courtyard riad, serving artisanal coffee, local herbal infusions, and home-baked pastries. The atmosphere is quiet and unhurried, popular with writers, artists, and travelers seeking refuge from the souk's energy. Walls are hung with rotating exhibitions by Tunisian contemporary artists.",
  },

  // ── TEA HOUSES ──
  {
    name: "Dar Zarrouk Tea House",
    category: PlaceCategory.TEA_HOUSE,
    address: "Sidi Bou Said Village, Main Street",
    city: "Sidi Bou Said",
    latitude: 36.8688,
    longitude: 10.342,
    rating: 4.6,
    reviewCount: 715,
    tags: [
      "mint tea",
      "Tunisian pastries",
      "riad",
      "traditional",
      "jasmine tea",
      "peaceful",
    ],
    description:
      "A peaceful tea house in a whitewashed riad in Sidi Bou Said, specializing in North African tea culture. The menu spans mint green tea with wormwood (thé à la menthe absinthe), jasmine-scented tea, and sage infusions, all served with traditional Tunisian pastries: baklava, kaak, and almond fingers dusted with sugar.",
  },
  {
    name: "Tozeur Oasis Tea Room",
    category: PlaceCategory.TEA_HOUSE,
    address: "Oasis District, Route des Palmerais",
    city: "Tozeur",
    latitude: 33.9197,
    longitude: 8.134,
    rating: 4.5,
    reviewCount: 298,
    tags: ["oasis", "date tea", "Tozeur", "desert", "palm grove", "relaxation"],
    description:
      "Hidden among the towering date palm groves of Tozeur's ancient oasis, this atmospheric tea room serves teas made from fresh dates, dried hibiscus, and local desert herbs. Sitting on cushions under palm canopy, surrounded by irrigation channels and birdsong, it is one of the most restorative experiences in southern Tunisia.",
  },

  // ── SHOPS ──
  {
    name: "Souk El Attarine — Spice and Perfume Market",
    category: PlaceCategory.SHOP,
    address: "Souk El Attarine, Medina",
    city: "Tunis",
    latitude: 36.798,
    longitude: 10.1692,
    rating: 4.5,
    reviewCount: 634,
    tags: [
      "spices",
      "perfumes",
      "Medina",
      "essential oils",
      "traditional",
      "shopping",
    ],
    description:
      "The historic perfumers' and spice merchants' souk in the heart of the Tunis Medina, where the air is permanently saturated with cumin, rose water, oud, and dried jasmine. Dozens of family-run stalls sell handmade essential oils, traditional kohl, orange blossom water, and spice blends impossible to find elsewhere.",
  },
  {
    name: "Atelier Damous — Handwoven Carpet Gallery",
    category: PlaceCategory.SHOP,
    address: "Rue de la Commission, Kairouan Medina",
    city: "Kairouan",
    latitude: 35.6833,
    longitude: 10.096,
    rating: 4.8,
    reviewCount: 412,
    tags: [
      "Kairouan carpet",
      "handwoven",
      "Berber kilim",
      "certified",
      "craft gallery",
      "artisan",
    ],
    description:
      "A certified artisan carpet gallery in the Kairouan Medina — the carpet capital of Tunisia — offering handwoven Berber kilims, traditional knotted rugs, and contemporary minimalist pieces. Each carpet carries an official ONAT certification guaranteeing authentic Tunisian production. The owner provides documentation of the weaver, region, and materials used.",
  },
  {
    name: "Nabeul Céramiques Artistiques",
    category: PlaceCategory.SHOP,
    address: "Avenue Habib Bourguiba, Nabeul",
    city: "Nabeul",
    latitude: 36.457,
    longitude: 10.738,
    rating: 4.4,
    reviewCount: 562,
    tags: [
      "ceramics",
      "Nabeul",
      "pottery",
      "cobalt blue",
      "handpainted",
      "artisan",
    ],
    description:
      "A working atelier and showroom in Nabeul selling exclusively handpainted ceramics produced on-site by a family of third-generation potters. The signature cobalt-and-white patterns draw on centuries of Nabeul tradition, with modern forms including espresso cups, tagine sets, and decorative tile panels. Custom commissions accepted.",
  },
  {
    name: "Mains de Femmes — Berber Textile Collective",
    category: PlaceCategory.SHOP,
    address: "Zone Artisanale, Gafsa",
    city: "Gafsa",
    latitude: 34.425,
    longitude: 8.784,
    rating: 4.7,
    reviewCount: 189,
    tags: [
      "women's cooperative",
      "Berber textiles",
      "kilim",
      "fair trade",
      "embroidery",
      "Gafsa",
    ],
    description:
      "A social enterprise shop operated by a women's weaving cooperative in Gafsa, selling Berber kilims, embroidered cushions, hand-spun wool garments, and natural-dyed textiles directly from the weavers. Each piece carries the maker's name and village. Fair trade certified and supported by international development organizations.",
  },

  // ── BAKERIES ──
  {
    name: "Boulangerie Ben Younes",
    category: PlaceCategory.BAKERY,
    address: "Rue Ibn Khaldoun, Tunis Centre",
    city: "Tunis",
    latitude: 36.8,
    longitude: 10.182,
    rating: 4.6,
    reviewCount: 833,
    tags: [
      "bread",
      "traditional bakery",
      "khoubz",
      "Tunisian pastry",
      "morning",
      "local",
    ],
    description:
      "A legendary neighborhood bakery in central Tunis, operating since 1961, known for its wood-fired khoubz taboun flatbread and traditional Tunisian morning pastries: bambalouni (fried doughnuts), ftayer (spinach pastry), and ghriba biscuits. Queue begins forming before dawn on weekends.",
  },
  {
    name: "Pâtisserie Masmoudi",
    category: PlaceCategory.BAKERY,
    address: "Avenue Bourguiba, Sfax",
    city: "Sfax",
    latitude: 34.741,
    longitude: 10.7615,
    rating: 4.8,
    reviewCount: 1456,
    tags: [
      "Tunisian sweets",
      "makroud",
      "baklava",
      "Sfax specialty",
      "pastry",
      "wedding sweets",
    ],
    description:
      "The most celebrated pastry house in Tunisia, founded in Sfax and now a national institution. Masmoudi's makroud — date-filled semolina pastry soaked in honey — is considered the definitive version. The Sfax flagship store also produces exclusive sweets for Ramadan and wedding ceremonies that are shipped across North Africa.",
  },

  // ── MARKETS ──
  {
    name: "Marché Central de Tunis",
    category: PlaceCategory.MARKET,
    address: "Rue Charles de Gaulle, Tunis",
    city: "Tunis",
    latitude: 36.7985,
    longitude: 10.1835,
    rating: 4.4,
    reviewCount: 2312,
    tags: [
      "covered market",
      "fresh produce",
      "fish",
      "meat",
      "spices",
      "local life",
    ],
    description:
      "Tunis's historic covered municipal market, a French colonial structure from 1891 still serving as the city's primary fresh food market. Stalls sell seasonal Tunisian vegetables, fresh Mediterranean fish landed that morning in La Goulette, wild herbs, charcuterie, and Tunisian honey. The best place to observe daily Tunisian market culture and buy picnic provisions.",
  },
  {
    name: "Douz Thursday Market",
    category: PlaceCategory.MARKET,
    address: "Market Square, Douz",
    city: "Douz",
    latitude: 33.457,
    longitude: 9.018,
    rating: 4.5,
    reviewCount: 387,
    tags: [
      "weekly market",
      "Douz",
      "desert market",
      "camel",
      "Berber",
      "spices",
      "dates",
    ],
    description:
      "A traditional Saharan weekly market held every Thursday in Douz, drawing nomadic Berber communities from surrounding oases and villages. The market sells desert truffles, dates, dried herbs, handwoven baskets, camel equipment, and silver Berber jewelry. One of the most authentic and unchanged market experiences in Tunisia.",
  },
  {
    name: "Nabeul Friday Souk",
    category: PlaceCategory.MARKET,
    address: "Town Centre, Nabeul",
    city: "Nabeul",
    latitude: 36.455,
    longitude: 10.736,
    rating: 4.3,
    reviewCount: 754,
    tags: [
      "weekly souk",
      "Nabeul",
      "ceramics",
      "produce",
      "Cap Bon",
      "textiles",
      "traditional",
    ],
    description:
      "The biggest weekly traditional market in Cap Bon, held every Friday across several blocks of central Nabeul. Farmers from surrounding villages sell citrus, jasmine, and seasonal produce alongside rows of ceramic vendors, fabric merchants, and spice sellers. The atmosphere peaks between 8am and 11am when locals do their weekly shopping.",
  },

  // ── BEAUTY SALONS ──
  {
    name: "Hammam El Kachachine",
    category: PlaceCategory.BEAUTY_SALON,
    address: "Rue El Kachachine, Medina",
    city: "Tunis",
    latitude: 36.7992,
    longitude: 10.1705,
    rating: 4.6,
    reviewCount: 547,
    tags: [
      "traditional hammam",
      "kessa",
      "black soap",
      "Medina",
      "authentic",
      "wellness",
    ],
    description:
      "One of the oldest surviving traditional hammams in the Tunis Medina, dating to the 17th century. The hammam operates on a public bathing schedule for men and women and offers a full traditional treatment: steam room, kessa exfoliation with savon beldi, rhassoul clay mask, and a cool-down room for rest and mint tea. A genuinely local, non-touristy experience.",
  },
  {
    name: "Nour Wellness Studio",
    category: PlaceCategory.BEAUTY_SALON,
    address: "Rue Hannibal, La Marsa",
    city: "La Marsa",
    latitude: 36.8875,
    longitude: 10.321,
    rating: 4.7,
    reviewCount: 321,
    tags: [
      "wellness",
      "aromatherapy",
      "hammam ritual",
      "La Marsa",
      "modern",
      "spa",
    ],
    description:
      "A contemporary wellness studio in La Marsa blending traditional Tunisian hammam rituals with modern spa practices. Offers full-body hammam packages using local argan oil and dried rose petals, alongside aromatherapy massages, reflexology, and facial treatments using indigenous Tunisian botanical extracts. Requires advance booking.",
  },

  // ── PHARMACIES ──
  {
    name: "Pharmacie el Andalous",
    category: PlaceCategory.PHARMACY,
    address: "Avenue Habib Bourguiba 45",
    city: "Tunis",
    latitude: 36.7998,
    longitude: 10.18,
    rating: 4.3,
    reviewCount: 234,
    tags: ["pharmacy", "central Tunis", "medical", "open late"],
    description:
      "A well-stocked central Tunis pharmacy on the main boulevard, with English and French-speaking staff. Carries a full range of prescription and over-the-counter medications, travel health supplies, and a selection of Tunisian medicinal plant products including dried herbs, argan oil, and prickly pear seed oil.",
  },
  {
    name: "Pharmacie du Golfe",
    category: PlaceCategory.PHARMACY,
    address: "Rue Principale, Tabarka",
    city: "Tabarka",
    latitude: 36.954,
    longitude: 8.759,
    rating: 4.2,
    reviewCount: 112,
    tags: ["pharmacy", "Tabarka", "medical", "coastal"],
    description:
      "The main pharmacy serving Tabarka and surrounding areas, stocking a broad range of medications, suncare, and first aid supplies appropriate for coastal activities and outdoor pursuits. The pharmacist speaks French and some English and can provide basic medical orientation for travelers.",
  },

  // ── Additional RESTAURANTS / CAFES ──
  {
    name: "Restaurant El Hana",
    category: PlaceCategory.RESTAURANT,
    address: "Corniche, Bizerte",
    city: "Bizerte",
    latitude: 37.2731,
    longitude: 9.8728,
    rating: 4.5,
    reviewCount: 478,
    tags: [
      "seafood",
      "Bizerte",
      "port",
      "grilled fish",
      "outdoor seating",
      "Mediterranean",
    ],
    description:
      "A waterfront seafood restaurant on the Bizerte corniche, famous throughout the region for freshly grilled Mediterranean fish and the city's signature recipe — Bizerte-style salade tunisienne with preserved lemon. The terrace overlooks the old port channel where fishing boats return each morning with the day's catch.",
  },
  {
    name: "Kasbah Café",
    category: PlaceCategory.CAFE,
    address: "Place de la Kasbah, Medina",
    city: "Tunis",
    latitude: 36.8,
    longitude: 10.169,
    rating: 4.3,
    reviewCount: 587,
    tags: [
      "Kasbah",
      "medina",
      "coffee",
      "outdoor terrace",
      "government square",
      "historic",
    ],
    description:
      "An open-air café on Place de la Kasbah facing the government palace and the Hafsid-era mosque. One of the few places in Tunis to drink coffee in the presence of living medieval architecture. A historic political gathering place that became famous worldwide during the 2011 revolution sit-ins.",
  },
  {
    name: "Chez Nous Tabarka",
    category: PlaceCategory.RESTAURANT,
    address: "Rue du Corail, Tabarka",
    city: "Tabarka",
    latitude: 36.9535,
    longitude: 8.758,
    rating: 4.4,
    reviewCount: 395,
    tags: [
      "Tabarka",
      "coral",
      "seafood",
      "Berber cooking",
      "local restaurant",
      "northern Tunisia",
    ],
    description:
      "A small family restaurant in Tabarka known for blending Tunisian coastal cooking with northern Berber mountain food traditions. Dishes include grilled red mullet with chermoula, stuffed peppers in harissa tomato sauce, and a distinctive house couscous with fresh herbs from the Kroumirie forest.",
  },
  {
    name: "Djerba Heritage Café",
    category: PlaceCategory.CAFE,
    address: "Houmt Souk Medina, Djerba",
    city: "Djerba",
    latitude: 33.8755,
    longitude: 10.8597,
    rating: 4.6,
    reviewCount: 632,
    tags: [
      "Djerba",
      "island café",
      "traditional",
      "mint tea",
      "Jewish quarter",
      "relaxed",
    ],
    description:
      "A shaded courtyard café in the Houmt Souk medina of Djerba, a short walk from the El Ghriba synagogue. Serves traditional Djerbian mint tea with dried figs and a menu of light island dishes reflecting the unique Judeo-Berber-Arab cultural synthesis that defines Djerba's identity. Favored by intellectuals and artists who visit the island.",
  },
  {
    name: "La Galite Boat Hire — Tabarka Harbour",
    category: PlaceCategory.SHOP,
    address: "Port de Pêche, Tabarka",
    city: "Tabarka",
    latitude: 36.9547,
    longitude: 8.7565,
    rating: 4.5,
    reviewCount: 143,
    tags: [
      "boat hire",
      "Tabarka",
      "fishing boat",
      "marine",
      "island trips",
      "coastal excursion",
    ],
    description:
      "A family-run boat hire and fishing excursion service operating out of Tabarka's fishing port. Offers day trips to La Galite island, sunset sailing along the Kroumirie coastline, and traditional line-fishing sessions with local captains. The fleet of wooden vessels is used both for guided marine tours and private charter. Advance booking essential for La Galite trips.",
  },
  {
    name: "Corniche Seafood Restaurants",
    category: PlaceCategory.RESTAURANT,
    address: "Corniche de La Goulette",
    city: "La Goulette",
    latitude: 36.82,
    longitude: 10.305,
    rating: 4.5,
    reviewCount: 892,
    tags: [
      "La Goulette",
      "port",
      "harissa tuna",
      "brik",
      "seafood",
      "weekend outing",
    ],
    description:
      "One of a row of beloved seafood restaurants along the La Goulette corniche — Tunis's port suburb and traditional destination for weekend fish lunches. Famous for the iconic Tunisian brik filled with tuna, capers, and egg, and a grilled fish selection that changes with the daily catch. Tables fill by noon on Fridays.",
  },
];

// ─── SEED FUNCTION ────────────────────────────────────────────────────────────

async function main() {
  console.log("🌱 Starting seed...");

  // Clear existing data in correct order
  // await prisma.booking.deleteMany();
  // await prisma.activity.deleteMany();
  // await prisma.place.deleteMany();
  // await prisma.housing.deleteMany();
  // await prisma.message.deleteMany();
  // await prisma.conversationParticipant.deleteMany();
  // await prisma.conversation.deleteMany();
  // await prisma.user.deleteMany();

  // console.log("🗑️  Cleared existing data");

  // ── Create Users ──
  const createdUsers = await Promise.all(
    usersData.map((u) => {
      const embeddingText = buildUserEmbeddingText(u.bio, u.interests);
      return prisma.user.upsert({
        where: { email: u.email },
        update: {
          fullName: u.fullName,
          password: u.password,
          role: u.role,
          bio: u.bio,
          interests: u.interests,
          embeddingText,
        },
        create: {
          email: u.email,
          fullName: u.fullName,
          password: u.password,
          role: u.role,
          bio: u.bio,
          interests: u.interests,
          embeddingText,
        },
      });
    }),
  );
  console.log(`✅ Created ${createdUsers.length} users`);

  // ── Create Activities ──
  const createdActivities = await Promise.all(
    activitiesData.map((a) => {
      const creator = createdUsers[a.creatorId];
      const embeddingText = buildActivityEmbeddingText(
        a.title,
        a.description,
        a.tags,
      );
      return prisma.activity.upsert({
        where: { title_creatorId: { title: a.title, creatorId: creator.id } },
        update: {
          description: a.description,
          price: a.price,
          date: a.date,
          location: a.location,
          latitude: a.latitude,
          longitude: a.longitude,
          capacity: a.capacity,
          category: a.category,
          status: a.status,
          images: [],
          tags: a.tags,
          embeddingText,
          creatorId: creator.id,
        },
        create: {
          title: a.title,
          description: a.description,
          price: a.price,
          date: a.date,
          location: a.location,
          latitude: a.latitude,
          longitude: a.longitude,
          capacity: a.capacity,
          category: a.category,
          status: a.status,
          images: [],
          tags: a.tags,
          embeddingText,
          creatorId: creator.id,
        },
      });
    }),
  );
  console.log(`✅ Created ${createdActivities.length} activities`);

  // ── Create Places ──
  const createdPlaces = await Promise.all(
    placesData.map((p) => {
      const embeddingText = buildPlaceEmbeddingText(
        p.name,
        p.description,
        p.tags,
      );
      return prisma.place.upsert({
        where: { name_city: { name: p.name, city: p.city } },
        update: {
          category: p.category,
          address: p.address,
          city: p.city,
          latitude: p.latitude,
          longitude: p.longitude,
          rating: p.rating ?? null,
          reviewCount: p.reviewCount ?? null,
          tags: p.tags,
          description: p.description,
          images: [],
          embeddingText,
        },
        create: {
          name: p.name,
          category: p.category,
          address: p.address,
          city: p.city,
          latitude: p.latitude,
          longitude: p.longitude,
          rating: p.rating ?? null,
          reviewCount: p.reviewCount ?? null,
          tags: p.tags,
          description: p.description,
          images: [],
          embeddingText,
        },
      });
    }),
  );
  console.log(`✅ Created ${createdPlaces.length} places`);

  console.log("\n🎉 Seed complete!");
  console.log(`   Users:      ${createdUsers.length}`);
  console.log(`   Activities: ${createdActivities.length}`);
  console.log(`   Places:     ${createdPlaces.length}`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
