export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            "colors": {
                "secondary-fixed": "#f5e0ba",
                "on-primary-fixed-variant": "#0e4688",
                "primary-fixed-dim": "#a9c7ff",
                "secondary": "#6b5d3e",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#d6e3ff",
                "primary": "#003873",
                "primary-container": "#1d4f91",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-surface": "#1b1c1a",
                "tertiary-fixed": "#ffdad3",
                "surface-bright": "#faf9f5",
                "on-primary": "#ffffff",
                "on-tertiary-fixed": "#3e0500",
                "inverse-surface": "#2f312e",
                "on-tertiary-fixed-variant": "#802918",
                "inverse-primary": "#a9c7ff",
                "on-secondary-container": "#706142",
                "secondary-container": "#f2ddb7",
                "outline": "#737782",
                "surface": "#faf9f5",
                "on-tertiary": "#ffffff",
                "outline-variant": "#c3c6d2",
                "on-surface-variant": "#434750",
                "error-container": "#ffdad6",
                "background": "#faf9f5",
                "surface-container-highest": "#e3e2df",
                "error": "#ba1a1a",
                "surface-container": "#efeeea",
                "surface-dim": "#dbdad6",
                "surface-container-low": "#f4f4f0",
                "on-secondary-fixed-variant": "#534529",
                "on-secondary-fixed": "#241a03",
                "on-secondary": "#ffffff",
                "tertiary-fixed-dim": "#ffb4a5",
                "tertiary": "#6d1b0c",
                "surface-tint": "#305ea1",
                "surface-container-high": "#e9e8e4",
                "on-background": "#1b1c1a",
                "on-primary-fixed": "#001b3e",
                "secondary-fixed-dim": "#d8c49f",
                "on-primary-container": "#a2c3ff",
                "tertiary-container": "#8c3220",
                "inverse-on-surface": "#f2f1ed",
                "surface-variant": "#e3e2df",
                "on-tertiary-container": "#ffae9d"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Noto Serif"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Plus Jakarta Sans"]
            }
        },
    },
    plugins: [],
}
